service:
  pipelines:
    metrics:
      receivers:
        - connections
        - mounts
        - exports
        - slabinfo
      processors:
        - resourcedetection
        - metricstransform
      exporters:
        - googlecloud
